% runs all bi-exponential voxelwise kidneys with RigidBiexp_Anatomic_voxelwise

% or tri-exp if edited to PN_Triexp_IVIM
%second input = 1: unlabelled kidney side (e.g. LP_C)
% = 2: left only (e.g. LK_LP_C)
% = 3: right only (e.g. RK_LP_C)
% sept 2023 ML 

RigidBiexp_Anatomic_voxelwise('P001')
RigidBiexp_Anatomic_voxelwise('P002',1)
RigidBiexp_Anatomic_voxelwise('P003',1)
RigidBiexp_Anatomic_voxelwise('P004')
RigidBiexp_Anatomic_voxelwise('P005')
RigidBiexp_Anatomic_voxelwise('P006')
RigidBiexp_Anatomic_voxelwise('P007')
RigidBiexp_Anatomic_voxelwise('P008')
RigidBiexp_Anatomic_voxelwise('P009')
RigidBiexp_Anatomic_voxelwise('P010')
RigidBiexp_Anatomic_voxelwise('P011')
RigidBiexp_Anatomic_voxelwise('P012')
RigidBiexp_Anatomic_voxelwise('P013')
RigidBiexp_Anatomic_voxelwise('P014')
RigidBiexp_Anatomic_voxelwise('P015')
RigidBiexp_Anatomic_voxelwise('P016')
RigidBiexp_Anatomic_voxelwise('P017')
RigidBiexp_Anatomic_voxelwise('P018')
RigidBiexp_Anatomic_voxelwise('P019')
RigidBiexp_Anatomic_voxelwise('P020')
RigidBiexp_Anatomic_voxelwise('P021')
RigidBiexp_Anatomic_voxelwise('P022')
RigidBiexp_Anatomic_voxelwise('P024')
RigidBiexp_Anatomic_voxelwise('P025')
RigidBiexp_Anatomic_voxelwise('P026')
RigidBiexp_Anatomic_voxelwise('P027')
RigidBiexp_Anatomic_voxelwise('P028')
RigidBiexp_Anatomic_voxelwise('P029')
RigidBiexp_Anatomic_voxelwise('P030')
RigidBiexp_Anatomic_voxelwise('P031')
RigidBiexp_Anatomic_voxelwise('P032')
RigidBiexp_Anatomic_voxelwise('P033')
RigidBiexp_Anatomic_voxelwise('P034')
RigidBiexp_Anatomic_voxelwise('P036')
RigidBiexp_Anatomic_voxelwise('P037')
RigidBiexp_Anatomic_voxelwise('P038')
RigidBiexp_Anatomic_voxelwise('P039')
RigidBiexp_Anatomic_voxelwise('P040')
RigidBiexp_Anatomic_voxelwise('P042')
RigidBiexp_Anatomic_voxelwise('P043')
RigidBiexp_Anatomic_voxelwise('P044')